In [33]:
import torch

In [100]:
input = torch.rand(1,2,5)
print(input)
# randint = torch.randint(5,(3,))
# # out=randint.transpose(0,2)
# print(randint.shape)


tensor([[[0.4599, 0.6607, 0.5605, 0.5421, 0.7378],
         [0.7383, 0.7016, 0.8863, 0.4592, 0.6458]]])


In [102]:
input1 = input[:,-1,:]
print(input1)

tensor([[0.7383, 0.7016, 0.8863, 0.4592, 0.6458]])


In [65]:
randint = torch.zeros(1,1)
print(randint)

tensor([[0.]])
